#:import plants plants
#:import navigation_screen_manager navigation_screen_manager
#:import boxlayout_action_bar boxlayout_action_bar
#:import home home

MyScreenManager:

<MyScreenManager>:
    home_screen: home_screen
    plants_window: plants_window

    Screen:
        name: "HomeScreen"
        id: home_screen
        HomeScreen:

    Screen:
        name: "PlantsWindow"
        id: plants_window
        BoxLayoutActionBar:
            title: "Home"
            PlantsWindow:









